% --- Helper function: convert 2-bit to grayscale ---
function img = to_grayscale(frame)
    img = uint8(...
        (frame == 3) * 255 + ...
        (frame == 2) * 125 + ...
        (frame == 1) * 80  + ...
        (frame == 0) * 0);
end
